[greeter]
background=/usr/share/omarchy/themes/tokyo-night/backgrounds/2-swirl-buck.jpg
user-background=false
theme-name=Adwaita-dark
icon-theme-name=Yaru-magenta
font-name=JetBrainsMono Nerd Font 12
default-user-image=/usr/share/omarchy/icon.png
round-user-image=false
transition-duration=0
transition-type=none
position=50%,center 50%,center
panel-position=top
clock-format=%H:%M
indicators=~session;~layout;~clock;~power
default-session=omarchy
